const SUPABASE_URL='https://rtnigoszuttbmyvzgscu.supabase.co';
const SUPABASE_KEY='sb_publishable_tnlE3wVwIT8RHkPXJb5-jQ_MxlwhnKR';
const ADMIN_EMAIL='pedro.rosa@itu.sp.gov.br'.toLowerCase();
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let authUser=null, authProfile=null;
function authMessage(t,erro=false){const e=document.getElementById('authMsg');if(!e)return;e.textContent=t;e.style.color=erro?'#a32620':'#176b3a';}
function escAdmin(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function isAdmin(){return (authUser?.email||'').toLowerCase()===ADMIN_EMAIL||authProfile?.funcao==='administrador';}
async function buscarPerfil(){if(!authUser)return null;const {data}=await sb.from('perfis').select('*').eq('id',authUser.id).maybeSingle();authProfile=data||null;return authProfile;}
async function aplicarSessao(session){authUser=session.user;await buscarPerfil();if(authProfile&&authProfile.ativo===false){await sb.auth.signOut();authMessage('Seu acesso está desativado. Fale com o administrador.',true);return;}document.getElementById('authGate').style.display='none';document.getElementById('sessionBar').style.display='flex';document.getElementById('sessionUser').textContent=authProfile?.nome||authUser.email;document.getElementById('sessionRole').textContent=isAdmin()?'Administrador':('Equipe'+(authProfile?.carro?' • '+authProfile.carro:''));document.getElementById('adminNav').style.display=isAdmin()?'inline-block':'none';try{await sb.from('perfis').update({ultimo_acesso:new Date().toISOString()}).eq('id',authUser.id);}catch(e){}await registrarAtividade('login',null,null,'Entrou no sistema');await sincronizarVisitas();}
async function bloquearSessao(){authUser=null;authProfile=null;document.getElementById('authGate').style.display='flex';document.getElementById('sessionBar').style.display='none';document.getElementById('adminNav').style.display='none';}
async function loginSistema(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authSenha').value;if(!email||!password)return authMessage('Informe e-mail e senha.',true);authMessage('Entrando...');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return authMessage('Não foi possível entrar: '+error.message,true);await aplicarSessao(data.session);}
async function criarAcessoSistema(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authSenha').value;if(!email||password.length<6)return authMessage('Use um e-mail válido e uma senha com pelo menos 6 caracteres.',true);const {error}=await sb.auth.signUp({email,password,options:{data:{nome:email.split('@')[0]}}});if(error)return authMessage(error.message,true);authMessage('Acesso criado. Se receber um e-mail de confirmação, confirme e depois clique em ENTRAR.');}
async function logoutSistema(){await registrarAtividade('logout',null,null,'Saiu do sistema');await sb.auth.signOut();await bloquearSessao();}
async function registrarAtividade(tipo,igreja,cidade,detalhes){if(!authUser)return;try{await sb.from('atividades').insert({usuario_id:authUser.id,tipo,igreja:igreja||null,cidade:cidade||null,detalhes:detalhes||null});}catch(e){console.warn(e.message)}}
async function sincronizarVisitas(){if(!authUser||typeof D==='undefined')return;try{const {data,error}=await sb.from('visitas').select('igreja,cidade,endereco,status').eq('status','visitada');if(error)throw error;(data||[]).forEach(v=>{const lista=D.cities[v.cidade]||[];let idx=lista.findIndex(x=>(x.name||'')===v.igreja&&(!v.endereco||(x.addr||'')===v.endereco));if(idx<0)idx=lista.findIndex(x=>(x.name||'')===v.igreja);if(idx>=0)state.visited[v.cidade+'|'+idx]=true;});save();renderRoute();renderAll();updateKpis();}catch(e){console.warn('sincronização',e.message)}}
const _toggleVisit=toggleVisit;toggleVisit=async function(city,idx){const k=city+'|'+idx,estava=!!state.visited[k],igreja=(D.cities[city]||[])[idx];_toggleVisit(city,idx);if(!authUser||!igreja)return;if(!estava&&state.visited[k]){await sb.from('visitas').insert({usuario_id:authUser.id,igreja:igreja.name,cidade:city,endereco:igreja.addr,equipe:authProfile?.equipe||null,carro:authProfile?.carro||null,status:'visitada'});await registrarAtividade('visita',igreja.name,city,'Marcou a igreja como visitada');}else if(estava&&!state.visited[k]){await sb.from('visitas').delete().eq('usuario_id',authUser.id).eq('igreja',igreja.name).eq('cidade',city);await registrarAtividade('visita_desfeita',igreja.name,city,'Removeu a marcação de visitada');}};
const _tab=tab;tab=function(id){_tab(id);if(authUser&&['rota','mapa','cal','todas'].includes(id))registrarAtividade('navegacao',null,null,'Abriu a aba '+id);};
async function atualizarPerfilAdmin(id,campo,valor){if(!isAdmin())return;const patch={};patch[campo]=valor;const {error}=await sb.from('perfis').update(patch).eq('id',id);if(error)alert(error.message);else carregarAdmin();}
async function carregarAdmin(){if(!isAdmin())return;const [pu,pa,pv]=await Promise.all([sb.from('perfis').select('*').order('nome'),sb.from('atividades').select('*').order('criado_em',{ascending:false}).limit(300),sb.from('visitas').select('*').order('visitada_em',{ascending:false}).limit(300)]);const users=pu.data||[],logs=pa.data||[],visits=pv.data||[],mapUsers=Object.fromEntries(users.map(u=>[u.id,u]));document.getElementById('admUsersCount').textContent=users.length;document.getElementById('admLogsCount').textContent=logs.length;document.getElementById('admVisitsCount').textContent=visits.length;const cutoff=Date.now()-86400000;document.getElementById('admTodayCount').textContent=logs.filter(x=>new Date(x.criado_em).getTime()>=cutoff).length;document.getElementById('admUsers').innerHTML='<table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Equipe</th><th>Carro</th><th>Último acesso</th><th>Status</th></tr></thead><tbody>'+users.map(u=>`<tr><td>${escAdmin(u.nome||'')}</td><td>${escAdmin(u.email||'')}</td><td><select onchange="atualizarPerfilAdmin('${u.id}','funcao',this.value)"><option ${u.funcao==='equipe'?'selected':''}>equipe</option><option value="administrador" ${u.funcao==='administrador'?'selected':''}>administrador</option></select></td><td><input style="width:100px" value="${escAdmin(u.equipe||'')}" onchange="atualizarPerfilAdmin('${u.id}','equipe',this.value)"></td><td><select onchange="atualizarPerfilAdmin('${u.id}','carro',this.value)"><option value="">—</option><option ${u.carro==='Carro A'?'selected':''}>Carro A</option><option ${u.carro==='Carro B'?'selected':''}>Carro B</option></select></td><td>${u.ultimo_acesso?new Date(u.ultimo_acesso).toLocaleString('pt-BR'):'—'}</td><td>${u.ativo===false?'Inativo':'Ativo'}</td></tr>`).join('')+'</tbody></table>';document.getElementById('admLogs').innerHTML='<table><thead><tr><th>Horário</th><th>Usuário</th><th>Atividade</th><th>Igreja/Cidade</th><th>Detalhes</th></tr></thead><tbody>'+logs.map(l=>`<tr><td>${new Date(l.criado_em).toLocaleString('pt-BR')}</td><td>${escAdmin(mapUsers[l.usuario_id]?.nome||mapUsers[l.usuario_id]?.email||l.usuario_id||'')}</td><td>${escAdmin(l.tipo)}</td><td>${escAdmin([l.igreja,l.cidade].filter(Boolean).join(' — '))}</td><td>${escAdmin(l.detalhes||'')}</td></tr>`).join('')+'</tbody></table>';document.getElementById('admVisits').innerHTML='<table><thead><tr><th>Horário</th><th>Usuário</th><th>Igreja</th><th>Cidade</th><th>Equipe/Carro</th></tr></thead><tbody>'+visits.map(v=>`<tr><td>${new Date(v.visitada_em||v.criado_em).toLocaleString('pt-BR')}</td><td>${escAdmin(mapUsers[v.usuario_id]?.nome||mapUsers[v.usuario_id]?.email||'')}</td><td>${escAdmin(v.igreja)}</td><td>${escAdmin(v.cidade||'')}</td><td>${escAdmin([v.equipe,v.carro].filter(Boolean).join(' • '))}</td></tr>`).join('')+'</tbody></table>';}
(async()=>{const {data}=await sb.auth.getSession();if(data.session)await aplicarSessao(data.session);else await bloquearSessao();sb.auth.onAuthStateChange(async(_,session)=>{if(session)await aplicarSessao(session);else await bloquearSessao();});})();