// Painel dedicado de cultos — edição por formulário modal.
(function(){
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
  function ensureUI(){
    const nav=document.querySelector('header nav');
    if(nav&&!document.getElementById('cultosNav')){const b=document.createElement('button');b.id='cultosNav';b.innerHTML='⛪ Cultos';b.onclick=()=>{tab('cultos');renderPainelCultos();};nav.insertBefore(b,document.getElementById('adminNav')||null);}
    const main=document.querySelector('main');
    if(main&&!document.getElementById('cultos')){const s=document.createElement('section');s.className='tab';s.id='cultos';s.innerHTML=`<div class="notice"><b>Painel de cultos.</b> Consulte e edite dias e horários. Informações não confirmadas aparecem como <b>A confirmar</b>.</div><div class="grid" style="margin-bottom:13px"><div class="card kpi"><span class="muted">Igrejas na base</span><b id="cultTotal">0</b></div><div class="card kpi"><span class="muted">Culto confirmado</span><b id="cultOk">0</b></div><div class="card kpi"><span class="muted">A confirmar</span><b id="cultPend">0</b></div><div class="card kpi"><span class="muted">Conflitos</span><b id="cultConflict">0</b></div></div><div class="card"><div class="toolbar"><select id="cultCity" onchange="renderPainelCultos()"></select><select id="cultStatus" onchange="renderPainelCultos()"><option value="all">Todos os status</option><option value="confirmado">Culto confirmado</option><option value="nao_confirmado">A confirmar</option><option value="conflito">Conflito</option></select><select id="cultDay" onchange="renderPainelCultos()"><option value="all">Todos os dias</option><option>Domingo</option><option>Segunda</option><option>Terça</option><option>Quarta</option><option>Quinta</option><option>Sexta</option><option>Sábado</option></select><input id="cultQ" oninput="renderPainelCultos()" placeholder="buscar igreja, cidade ou endereço" style="min-width:260px"/></div><div class="admin-table-wrap" id="cultTable"></div></div>`;main.appendChild(s);}
    if(!document.getElementById('cultEditModal')){const m=document.createElement('div');m.id='cultEditModal';m.style.cssText='display:none;position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:99999;align-items:center;justify-content:center;padding:18px';m.innerHTML=`<div class="card" style="width:min(620px,96vw);max-height:90vh;overflow:auto"><h2 style="margin-top:0">Editar culto</h2><div id="cultEditChurch" class="notice" style="margin-bottom:12px"></div><input type="hidden" id="ceCity"><input type="hidden" id="ceName"><input type="hidden" id="ceAddr"><label><b>Prioridade</b></label><select id="cePrior" style="width:100%;margin:5px 0 12px"><option value="alta">Alta</option><option value="normal">Normal</option><option value="baixa">Baixa</option></select><label><b>Status</b></label><select id="ceStatus" style="width:100%;margin:5px 0 12px"><option value="confirmado">Confirmado</option><option value="nao_confirmado">A confirmar</option><option value="conflito">Conflito</option></select><label><b>Dias de culto</b></label><input id="ceDias" style="width:100%;margin:5px 0 12px" placeholder="Ex.: Qua 19h30; Dom 19h"><label><b>Horário principal</b></label><input id="ceHora" style="width:100%;margin:5px 0 12px" placeholder="Ex.: 19h30"><label><b>Fonte / link</b></label><input id="ceFonte" style="width:100%;margin:5px 0 12px" placeholder="Link ou observação da fonte"><label><b>Observação</b></label><textarea id="ceObs" style="width:100%;min-height:70px;margin:5px 0 14px"></textarea><div style="display:flex;gap:8px;justify-content:flex-end"><button class="btn secondary" onclick="fecharEditorCulto()">Cancelar</button><button class="btn" id="ceSave" onclick="salvarEditorCulto()">Salvar alterações</button></div></div>`;document.body.appendChild(m);}
    const city=document.getElementById('cultCity');if(city&&city.options.length===0)city.innerHTML='<option value="ALL">Todas as cidades</option>'+Object.keys(D.cities||{}).sort((a,b)=>a.localeCompare(b,'pt-BR')).map(c=>`<option>${esc(c)}</option>`).join('');
  }
  function normDay(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
  window.abrirEditorCulto=function(c,n,a){if(typeof isAdmin!=='function'||!isAdmin())return alert('Somente o administrador pode editar cultos.');ensureUI();const x=typeof cfgDaIgreja==='function'?cfgDaIgreja(c,n,a):{};document.getElementById('ceCity').value=c;document.getElementById('ceName').value=n;document.getElementById('ceAddr').value=a||'';document.getElementById('cePrior').value=x.prioridade||'normal';document.getElementById('ceStatus').value=x.culto_status||'nao_confirmado';document.getElementById('ceDias').value=x.culto_dias||'';document.getElementById('ceHora').value=x.culto_horario||'';document.getElementById('ceFonte').value=x.culto_fonte||'';document.getElementById('ceObs').value=x.observacao||'';document.getElementById('cultEditChurch').innerHTML='<b>'+esc(n)+'</b><br>'+esc(c)+' — '+esc(a||'');document.getElementById('cultEditModal').style.display='flex';};
  window.fecharEditorCulto=function(){const m=document.getElementById('cultEditModal');if(m)m.style.display='none';};
  window.salvarEditorCulto=async function(){const b=document.getElementById('ceSave');const c=document.getElementById('ceCity').value,n=document.getElementById('ceName').value,a=document.getElementById('ceAddr').value;const patch={prioridade:document.getElementById('cePrior').value,culto_status:document.getElementById('ceStatus').value,culto_dias:document.getElementById('ceDias').value.trim(),culto_horario:document.getElementById('ceHora').value.trim(),culto_fonte:document.getElementById('ceFonte').value.trim(),observacao:document.getElementById('ceObs').value.trim()};try{b.disabled=true;b.textContent='Salvando...';await salvarCfgIgreja(c,n,a,patch);fecharEditorCulto();if(typeof renderPainelCultos==='function')renderPainelCultos();}catch(e){alert('Não foi possível salvar: '+(e.message||e));}finally{b.disabled=false;b.textContent='Salvar alterações';}};
  window.renderPainelCultos=function(){ensureUI();const all=typeof allChurches==='function'?allChurches():[];const city=document.getElementById('cultCity')?.value||'ALL',status=document.getElementById('cultStatus')?.value||'all',day=document.getElementById('cultDay')?.value||'all',q=(document.getElementById('cultQ')?.value||'').toLowerCase();let arr=all.map(x=>({x,cfg:typeof cfgDaIgreja==='function'?cfgDaIgreja(x.city,x.name,x.addr):{}}));const total=arr.length,ok=arr.filter(z=>z.cfg.culto_status==='confirmado').length,conf=arr.filter(z=>z.cfg.culto_status==='conflito').length;document.getElementById('cultTotal').textContent=total;document.getElementById('cultOk').textContent=ok;document.getElementById('cultConflict').textContent=conf;document.getElementById('cultPend').textContent=total-ok-conf;if(city!=='ALL')arr=arr.filter(z=>z.x.city===city);if(status!=='all')arr=arr.filter(z=>(z.cfg.culto_status||'nao_confirmado')===status);if(day!=='all')arr=arr.filter(z=>normDay(z.cfg.culto_dias).includes(normDay(day).slice(0,4)));if(q)arr=arr.filter(z=>(z.x.city+' '+z.x.name+' '+z.x.addr+' '+(z.cfg.culto_dias||'')+' '+(z.cfg.culto_horario||'')).toLowerCase().includes(q));const rank={confirmado:0,conflito:1,nao_confirmado:2};arr.sort((a,b)=>(rank[a.cfg.culto_status||'nao_confirmado']-rank[b.cfg.culto_status||'nao_confirmado'])||a.x.city.localeCompare(b.x.city,'pt-BR'));const rows=arr.map(({x,cfg})=>{const st=cfg.culto_status||'nao_confirmado',label=st==='confirmado'?'🟢 Confirmado':st==='conflito'?'🔴 Conflito':'🟡 A confirmar';const src=cfg.culto_fonte?`<a class="maplink" href="${esc(cfg.culto_fonte)}" target="_blank">Fonte ↗</a>`:'—';const edit=(typeof isAdmin==='function'&&isAdmin())?`<button type="button" class="btn secondary" style="padding:6px 10px" onclick='abrirEditorCulto(${JSON.stringify(x.city)},${JSON.stringify(x.name)},${JSON.stringify(x.addr)})'>✏️ Editar</button>`:'';return `<tr><td><b>${esc(x.city)}</b></td><td><b>${esc(x.name)}</b><div class="small muted">${esc(x.addr)}</div></td><td>${esc(cfg.culto_dias||'A confirmar')}</td><td>${esc(cfg.culto_horario||'—')}</td><td>${label}</td><td>${esc(cfg.prioridade||'normal')}</td><td>${src}</td><td>${edit}</td></tr>`;}).join('');document.getElementById('cultTable').innerHTML=`<table><thead><tr><th>Cidade</th><th>Igreja / Endereço</th><th>Dia(s) de culto</th><th>Horário</th><th>Status</th><th>Prioridade</th><th>Fonte</th><th>Ação</th></tr></thead><tbody>${rows||'<tr><td colspan="8">Nenhuma igreja encontrada.</td></tr>'}</tbody></table>`;};
  ensureUI();setTimeout(ensureUI,500);setTimeout(()=>{if(document.getElementById('cultos')?.classList.contains('active'))renderPainelCultos();},1200);
})();