// Camada operacional adicional — preserva a base/rotas existentes.
let igrejaCfg={};
const cfgKey=(c,n,a)=>[c,n,a||''].join('|');
async function carregarIgrejaCfg(){if(typeof sb==='undefined'||!authUser)return;const {data,error}=await sb.from('igrejas_config').select('*');if(error){console.warn(error.message);return;}igrejaCfg={};(data||[]).forEach(x=>igrejaCfg[cfgKey(x.cidade,x.igreja,x.endereco)]=x);if(typeof renderRoute==='function')renderRoute();if(typeof renderAll==='function')renderAll();}
function cfgDaIgreja(c,n,a){return igrejaCfg[cfgKey(c,n,a)]||{};}
function prioridadeBadge(c,n,a){const p=cfgDaIgreja(c,n,a).prioridade||'normal';return p==='alta'?'⭐ PRIORIDADE':p==='baixa'?'▫ BAIXA':'• NORMAL';}
function cultoBadge(c,n,a){const x=cfgDaIgreja(c,n,a),s=x.culto_status||'nao_confirmado';return s==='confirmado'?'🟢 CULTO CONFIRMADO':s==='conflito'?'🔴 CONFLITO DE CULTO':'🟡 CULTO A CONFIRMAR';}
async function salvarCfgIgreja(c,n,a,patch){if(!isAdmin())return alert('Somente o administrador pode alterar estes dados.');const atual=cfgDaIgreja(c,n,a);const payload={cidade:c,igreja:n,endereco:a||'',prioridade:atual.prioridade||'normal',culto_status:atual.culto_status||'nao_confirmado',...patch,atualizado_por:authUser.id};const {data,error}=await sb.from('igrejas_config').upsert(payload,{onConflict:'cidade,igreja,endereco'}).select().single();if(error)return alert(error.message);igrejaCfg[cfgKey(c,n,a)]=data;await registrarAtividade('config_igreja',n,c,'Atualizou prioridade/culto');renderRoute();renderAll();}
function editarOperacaoIgreja(c,n,a){if(!isAdmin())return;const x=cfgDaIgreja(c,n,a);const prioridade=prompt('Prioridade: alta, normal ou baixa',x.prioridade||'normal');if(prioridade===null)return;const status=prompt('Culto: confirmado, conflito ou nao_confirmado',x.culto_status||'nao_confirmado');if(status===null)return;const dias=prompt('Dias de culto (ex.: Qua 19h30; Dom 19h)',x.culto_dias||'')??x.culto_dias;const horario=prompt('Horário principal',x.culto_horario||'')??x.culto_horario;const fonte=prompt('Fonte/link da confirmação',x.culto_fonte||'')??x.culto_fonte;salvarCfgIgreja(c,n,a,{prioridade:['alta','normal','baixa'].includes(prioridade)?prioridade:'normal',culto_status:['confirmado','conflito','nao_confirmado'].includes(status)?status:'nao_confirmado',culto_dias:dias,culto_horario:horario,culto_fonte:fonte});}
const oldRenderRoute=renderRoute;renderRoute=function(){oldRenderRoute();document.querySelectorAll('#routeCards .stop').forEach((el,i)=>{const x=(D.routes[activeDay]||[])[i];if(!x)return;const cfg=cfgDaIgreja(x.city,x.name,x.addr);const info=document.createElement('div');info.className='small';info.style.marginTop='6px';info.innerHTML=`<b>${prioridadeBadge(x.city,x.name,x.addr)}</b> · ${cultoBadge(x.city,x.name,x.addr)}${cfg.culto_dias?`<br>⛪ ${cfg.culto_dias}${cfg.culto_horario?' · '+cfg.culto_horario:''}`:''}${isAdmin()?` <button class="btn secondary" style="padding:4px 8px;margin-left:5px" onclick="editarOperacaoIgreja(${JSON.stringify(x.city)},${JSON.stringify(x.name)},${JSON.stringify(x.addr)})">Editar</button>`:''}`;const mid=el.children[1];if(mid)mid.appendChild(info);});};
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();const rows=document.querySelectorAll('#allTable tbody tr');let arr=[];const city=document.getElementById('cityFilter').value,q=(document.getElementById('q').value||'').toLowerCase(),st=document.getElementById('statusFilter').value;arr=city==='ALL'?allChurches():allChurches().filter(x=>x.city===city);arr=arr.filter(x=>(x.name+' '+x.addr+' '+x.city).toLowerCase().includes(q));if(st!=='all')arr=arr.filter(x=>st==='done'?!!state.visited[x.city+'|'+x.idx]:!state.visited[x.city+'|'+x.idx]);rows.forEach((r,i)=>{const x=arr[i];if(!x)return;const td=document.createElement('td');td.innerHTML=`<span class="small"><b>${prioridadeBadge(x.city,x.name,x.addr)}</b><br>${cultoBadge(x.city,x.name,x.addr)}</span>${isAdmin()?`<br><button class="btn secondary" style="padding:4px 8px;margin-top:4px" onclick="editarOperacaoIgreja(${JSON.stringify(x.city)},${JSON.stringify(x.name)},${JSON.stringify(x.addr)})">Editar</button>`:''}`;r.appendChild(td);});const h=document.querySelector('#allTable thead tr');if(h&&!h.querySelector('.ophead')){const th=document.createElement('th');th.className='ophead';th.textContent='Prioridade / Culto';h.appendChild(th);}};
const oldAplicarSessao=aplicarSessao;aplicarSessao=async function(session){await oldAplicarSessao(session);await carregarIgrejaCfg();};
setTimeout(()=>{if(authUser)carregarIgrejaCfg();},1200);
// Carrega a camada eleitoral aprimorada sem alterar a base operacional.
(function(){const s=document.createElement('script');s.src='election-enhanced.js?v=1';s.defer=false;document.body.appendChild(s);})();
