const D=window.D;

let state=JSON.parse(localStorage.getItem('rota_igrejas_final')||'{"visited":{}}');
let activeDay=0, map=null, eMap=null, markers=[]; let calCursor=new Date('2026-08-25T00:00:00');
const start=new Date('2026-08-25T00:00:00');
function allChurches(){let a=[];for(const [city,arr] of Object.entries(D.cities))arr.forEach((x,i)=>a.push({city,idx:i,...x}));return a}
function save(){localStorage.setItem('rota_igrejas_final',JSON.stringify(state))}
function tab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='mapa')setTimeout(initMap,80);if(id==='eleitoral')setTimeout(initElectoral,100);if(id==='cal')setTimeout(renderCal,50)}
function dateFor(i){let d=new Date(start);d.setDate(start.getDate()+i);return d}
function dk(d){return d.toISOString().slice(0,10)}
function pt(d){return d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit'})}
function toggleVisit(city,idx){const k=city+'|'+idx;state.visited[k]=!state.visited[k];save();renderRoute();renderAll();updateKpis();}
const VERIFY_STOP={"0|0":{status:"conflict",text:"A programação pública consultada informa reunião de oração na segunda, estudo bíblico na quarta (19h30), culto na sexta (19h30) e culto da família no domingo (19h). Terça-feira não aparece como culto publicado.",source:"https://addeus-sorocaba.webnode.page/horarios-dos-cultos/"},"14|3":{status:"conflict",text:"A programação pública da AD Ipiranga informa terça-feira fechada; os horários publicados incluem quarta, sábado e domingo. Por isso, 08/09/2026 é conflito com a grade publicada.",source:"https://www.locaisdobrasil.com.br/encontre/igreja/mogi-guacu-sp/assembleia-de-deus-ipiranga-mogi-guacu/658355ef3a218469044665a6"},"26|3":{status:"compatible",text:"A programação pública consultada informa culto aos domingos às 18h e às quartas às 19h30. Domingo 20/09/2026 é compatível com a grade publicada.",source:"https://www.youtube.com/watch?v=1irwVvRdCF4"},"1|15":{status:"unverified",text:"Encontrei programação pública para uma congregação do Jardim Guaíba às quartas-feiras, mas o endereço publicado é diferente do endereço desta rota. Não apliquei como confirmação automática.",source:"https://www.findglocal.com/BR/Sorocaba/100698988737524/Assembleia-De-Deus-Min.Bel%C3%A9m--Jardim-Gua%C3%ADba"}};
function verifyFor(x,dayIndex){return VERIFY_STOP[dayIndex+'|'+x._routeIndex]||{status:'unverified',text:'Não localizei uma programação pública atual e específica para este endereço. A visita deve ser confirmada com a congregação antes da saída.',source:null};}
function renderVerify(){const items=(D.routes[activeDay]||[]).map((x,i)=>({...x,_routeIndex:i}));document.getElementById('verifyDay')&&(document.getElementById('verifyDay').innerHTML='<div class="verify-grid">'+items.map((x,i)=>{let v=verifyFor(x,activeDay),cl=v.status==='compatible'?'v-ok':v.status==='conflict'?'v-bad':'v-warn';let lab=v.status==='compatible'?'COMPATÍVEL':v.status==='conflict'?'CONFLITO':'NÃO CONFIRMADO';return `<div class="verify-card ${cl}"><div><b>${i+1}. ${x.name}</b></div><span class="vbadge">${lab}</span><div class="small" style="margin-top:6px">${v.text}</div>${v.source?`<a class="small" target="_blank" href="${v.source}">Fonte ↗</a>`:''}</div>`}).join('')+'</div>');}
function renderRoute(){const items=D.routes[activeDay]||[],d=dateFor(activeDay);document.getElementById('dayTitle').textContent=pt(d);document.getElementById('dayMeta').textContent='Saída de Itu → 8 desembarques previstos → retorno';const A=items.slice(0,4),B=items.slice(4,8);const card=(label,arr,offset)=>`<div class="card"><div class="car-title"><b>🚗 ${label}</b><span class="small muted">${arr.length} pessoas</span></div>${arr.map((x,i)=>{let done=!!state.visited[x.city+'|'+x.idx];return `<div class="stop ${done?'done':''}"><div class="num">${i+1}</div><div><div class="small muted">PESSOA ${offset+i+1} · FICA NESTA IGREJA</div><b>${x.name}</b><div class="small">${x.addr}</div></div><div><button class="check ${done?'done':''}" onclick="toggleVisit('${x.city.replace(/'/g,"\\'")}',${x.idx})">${done?'✓ VISITADA':'MARCAR VISITADA'}</button><br><a class="maplink" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(x.addr)}">🗺️ Navegar</a></div></div>`}).join('')}</div>`;document.getElementById('routeCards').innerHTML=`<div class="cargrid">${card('CARRO A',A,0)}${card('CARRO B',B,4)}</div>`;renderVerify();document.getElementById('dayButtons').innerHTML=Array.from({length:28},(_,i)=>`<button class="btn ${i===activeDay?'':'secondary'}" onclick="activeDay=${i};renderRoute();updateMapDay()">${i+1}º dia</button>`).join('');}
function renderAll(){const city=document.getElementById('cityFilter').value,q=(document.getElementById('q').value||'').toLowerCase(),st=document.getElementById('statusFilter').value;let arr=city==='ALL'?allChurches():Object.entries(D.cities).filter(([c])=>c===city).flatMap(([c,v])=>v.map((x,i)=>({city:c,idx:i,...x})));arr=arr.filter(x=>(x.name+' '+x.addr+' '+x.city).toLowerCase().includes(q));if(st!=='all')arr=arr.filter(x=>st==='done'?!!state.visited[x.city+'|'+x.idx]:!state.visited[x.city+'|'+x.idx]);let rows=arr.map(x=>{let done=!!state.visited[x.city+'|'+x.idx];return `<tr class="${done?'visited':''}"><td>${done?'🟢':'⚪'}</td><td><b>${x.city}</b></td><td><b>${x.name}</b></td><td>${x.addr}</td><td><button class="check ${done?'done':''}" onclick="toggleVisit('${x.city.replace(/'/g,"\\'")}',${x.idx})">${done?'✓ VISITADA':'MARCAR VISITADA'}</button></td></tr>`}).join('');document.getElementById('allTable').innerHTML=`<table><thead><tr><th>Status</th><th>Cidade</th><th>Igreja</th><th>Endereço</th><th></th></tr></thead><tbody>${rows}</tbody></table>`;}
function updateKpis(){const n=allChurches().length,done=Object.values(state.visited).filter(Boolean).length;document.getElementById('nChurch').textContent=n;document.getElementById('nCities').textContent=Object.keys(D.cities).length;document.getElementById('nRemain').textContent=Math.max(0,n-224);let p=n?Math.min(100,done/n*100):0;document.getElementById('prog').style.width=p+'%';document.getElementById('progText').textContent=`${done} visitadas de ${n} cadastradas (${p.toFixed(1)}%).`;}
function initMap(){if(map)return;map=L.map('map').setView([-23.5,-47.3],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);updateMapDay();}
function updateMapDay(){if(!map)return;markers.forEach(m=>map.removeLayer(m));markers=[];let items=D.routes[activeDay]||[];document.getElementById('mapStops').innerHTML=items.map((x,i)=>`<div class="pill">${i+1}. ${x.city} — ${x.name} ${state.visited[x.city+'|'+x.idx]?'🟢':''}</div>`).join('');items.forEach((x,i)=>{let c=D.coords[x.city];if(c){let m=L.circleMarker(c,{radius:8,fillColor:state.visited[x.city+'|'+x.idx]?'#176b3a':'#9ac8a7',color:'#155b33',fillOpacity:.9}).addTo(map).bindPopup(`<b>${i+1}. ${x.name}</b><br>${x.addr}<br>${state.visited[x.city+'|'+x.idx]?'✓ visitada':'pendente'}`);markers.push(m);}})}
function openDayMaps(){let items=D.routes[activeDay]||[];if(!items.length)return;for(let car=0;car<2;car++){let arr=items.slice(car*4,car*4+4);if(!arr.length)continue;let dest=arr[arr.length-1].addr,way=arr.slice(0,-1).map(x=>encodeURIComponent(x.addr)).join('|');setTimeout(()=>window.open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent('Itu, SP')}&destination=${encodeURIComponent(dest)}&waypoints=${way}`,'_blank'),car*250);}}
function locateMe(){if(!navigator.geolocation)return alert('Seu navegador não disponibiliza localização.');navigator.geolocation.getCurrentPosition(p=>{if(map){L.marker([p.coords.latitude,p.coords.longitude]).addTo(map).bindPopup('📍 Você está aqui').openPopup();map.setView([p.coords.latitude,p.coords.longitude],13)}},()=>alert('Permita acesso à localização no navegador.'));}
function renderElectionCities(){const q=(document.getElementById('eq').value||'').toLowerCase(),arr=(D.election||[]).filter(x=>x.city.toLowerCase().includes(q));document.getElementById('eCityTable').innerHTML='<table><thead><tr><th>Cidade</th><th>Votos</th><th>Visual</th></tr></thead><tbody>'+arr.map(x=>`<tr><td>${x.city}</td><td>${x.votes==null?'—':x.votes.toLocaleString('pt-BR')}</td><td>${x.votes==null?'<span class="muted">Consultar TSE</span>':'<div class="statbar"><span style="width:'+Math.min(100,Math.max(2,x.votes/164.93))+'%"></span></div>'}</td></tr>`).join('')+'</tbody></table>';}
function initElectoral(){if(eMap)return;eMap=L.map('eMap').setView([-23.5,-47.2],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(eMap);(D.election||[]).forEach(x=>{let intensity=x.votes==null?0.1:Math.min(1,x.votes/16493);let color=x.votes==null?'#cfdad1':(intensity>.25?'#145c31':intensity>.08?'#4b9261':'#a7cfb2');L.circleMarker([x.lat,x.lon],{radius:x.votes?Math.max(6,Math.min(20,6+x.votes/1200)):5,fillColor:color,color:'#1a5633',fillOpacity:.82}).addTo(eMap).bindPopup(`<b>${x.city}</b><br>${x.votes==null?'Votação não carregada nesta visão local':'Rita: '+x.votes.toLocaleString('pt-BR')+' votos'}`);});}
function renderElectionBars(){const a=D.knownElection||[];document.getElementById('eBars').innerHTML=a.map(x=>`<div style="margin:8px 0"><div style="display:flex;justify-content:space-between"><b>${x.city}</b><span>${x.votes.toLocaleString('pt-BR')} votos</span></div><div class="statbar"><span style="width:${Math.min(100,6+x.votes/164.93)}%"></span></div><div class="small muted">${x.share_city}% dos votos da cidade · ${x.share_campaign}% da votação de Rita</div></div>`).join('');}
function calMove(n){calCursor.setMonth(calCursor.getMonth()+n);renderCal()}function calReset(){calCursor=new Date(start);renderCal()}
function renderCal(){const y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0);let o='<div class="calendar">';['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].forEach(x=>o+=`<div class="wd">${x}</div>`);for(let i=0;i<first.getDay();i++)o+='<div></div>';for(let d=1;d<=last.getDate();d++){const dt=new Date(y,m,d),idx=Math.floor((dt-start)/86400000),items=D.routes[idx]||[];o+=`<div class="cal ${dk(dt)===dk(new Date())?'today':''}"><b>${d}</b>${items.length?items.slice(0,8).map(x=>`<div class="pill">${x.city} — ${x.name}</div>`).join(''):'<div class="small muted">sem rota</div>'}</div>`}o+='</div>';document.getElementById('calGrid').innerHTML=o;}
const citySel=document.getElementById('cityFilter');citySel.innerHTML='<option value="ALL">Todas as cidades</option>'+Object.keys(D.cities).map(c=>`<option>${c}</option>`).join('');document.getElementById('mapDay').innerHTML=Array.from({length:28},(_,i)=>`<option value="${i}">${i+1}º dia — ${pt(dateFor(i))}</option>`).join('');document.getElementById('mapDay').addEventListener('change',e=>{activeDay=+e.target.value;renderRoute();updateMapDay();});document.getElementById('nPlan').textContent=D.routes.reduce((a,v)=>a+v.length,0);renderRoute();renderAll();updateKpis();renderCal();renderElectionBars();renderElectionCities();